"""database init

Revision ID: aecf5ce66032
Revises: 
Create Date: 2023-09-27 14:59:46.978689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecf5ce66032'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_product_id', sa.String(length=11), nullable=True),
    sa.Column('exchange_product_name', sa.String(), nullable=True),
    sa.Column('oil_id', sa.String(length=4), nullable=True),
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=True),
    sa.Column('delivery_basis_name', sa.String(), nullable=True),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spimex_trading_results')
    # ### end Alembic commands ###
